name: dbt_crm
version: '1.0'
config-version: 2

profile: my_project

model-paths: ["models"]

models:
  dbt_crm:

    stg:
      +schema: staging
      +materialized: view

    int:
      +schema: intermediate
      +materialized: view

    dp:
      +schema: data_products
      +materialized: table