version: 2

sources:
  - name: wheelie
    database: mm-bigdata-2026-data-mesh
    schema: wheelie_crm_shared
    tables:
      - name: customer
      - name: address
      - name: city
      - name: country
      - name: equipment
      - name: car
      - name: inventory
      - name: inventory_equipment
      - name: payment
      - name: rental
      - name: service
      - name: staff
      - name: store
      
  - name: wheelie_sales_products
    database: data-mesh-pk
    schema: wheelie_sales_products
    tables:
      - name: dp_customer_sales_activity
      - name: dp_rental_events
      - name: dp_payment_transactions
      - name: dp_rental_payment_ledger

  - name: crm_data_products
    database: bw-bigdata-2026-data-mesh
    #schema: crm_data_products
    schema: crm
    tables:
      - name: dp_customer_profile_secure
      - name: dp_customer_segmentation
      - name: dp_customer_profile


  - name: fleet
    database: pr-bigdata-2026-data-mesh
    schema: fleet_domain_data_products
    tables:
      - name: dp_car_catalog

  - name: crm_survey
    database: bw-bigdata-2026-data-mesh
    schema: crm
    tables:
      - name: survey_responses
        description: >
          Post-rental customer satisfaction surveys sent automatically
          via email link one day after payment. Each response is tied
          to a specific rental and customer.    