version: 2

sources:
  - name: wheelie
    database: mm-bigdata-2026-data-mesh
    schema: wheelie_crm_shared
    tables:
      - name: customer
      - name: address
      - name: city
      - name: country
      - name: equipment
      - name: car
      - name: inventory
      - name: inventory_equipment
      - name: payment
      - name: rental
      - name: service
      - name: staff
      - name: store
      
  - name: wheelie_sales_products
    database: data-mesh-pk
    schema: wheelie_sales_products
    tables:
      - name: dp_customer_sales_activity

  - name: crm_data_products
    database: bw-bigdata-2026-data-mesh
    #schema: crm_data_products
    schema: crm
    tables:
      - name: dp_customer_profile_secure
      - name: dp_customer_segmentation
      - name: dp_customer_profile